name: Python pytest

on:
  push:
    branches:
      - "**"  # Adjust this to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Use the Python version your project requires

      - name: Install dependencies
        run: pip install -r isr-backend/requirements.txt  # Modify as needed

      - name: Run pytest
        run: python -m pytest
